import 'dotenv/config';
import express from 'express';
import mysql from 'mysql2/promise';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const app = express();
const port = Number(process.env.PORT || 3000);
const prefix = (process.env.DB_TABLE_PREFIX || 'wp_').replace(/[^a-zA-Z0-9_]/g, '');
const table = (name) => `\`${prefix}el_roi_${name}\``;
const missingDbConfig = ['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASSWORD'].filter((key) => !process.env[key]);
if (missingDbConfig.length) {
  console.error(`Database configuration missing: ${missingDbConfig.join(', ')}. Set these variables in Hostinger before starting the Node.js app.`);
  process.exit(1);
}
const pool = mysql.createPool({ host: process.env.DB_HOST, port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER, password: process.env.DB_PASSWORD, database: process.env.DB_NAME, waitForConnections: true, connectionLimit: 10, charset: 'utf8mb4', dateStrings: true });
const sessions = new Map();
app.use(express.json({ limit: '2mb' }));
app.use((req, _res, next) => { req.cookies = Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map((part) => { const [key, ...value] = part.trim().split('='); return [key, decodeURIComponent(value.join('='))]; })); next(); });
app.use((req, res, next) => { const origin = process.env.CORS_ORIGIN; if (origin) { res.header('Access-Control-Allow-Origin', origin); res.header('Access-Control-Allow-Credentials', 'true'); res.header('Access-Control-Allow-Headers', 'Content-Type'); res.header('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS'); } if (req.method === 'OPTIONS') return res.sendStatus(204); next(); });
async function initDb() {
  await pool.query(`CREATE TABLE IF NOT EXISTS ${table('songs')} (id VARCHAR(80) PRIMARY KEY, title VARCHAR(255) NOT NULL, artist VARCHAR(255) NOT NULL DEFAULT '', category VARCHAR(255) NOT NULL, language VARCHAR(80) NOT NULL, cover_image TEXT, lyrics LONGTEXT NOT NULL, chords_lyrics LONGTEXT, default_key VARCHAR(20), bpm INT NULL, tempo VARCHAR(20), video_url TEXT, audio_url TEXT, media_links LONGTEXT, is_pinned TINYINT(1) NOT NULL DEFAULT 0, is_favorite TINYINT(1) NOT NULL DEFAULT 0, views INT NOT NULL DEFAULT 0, year INT NULL, status VARCHAR(20) NOT NULL DEFAULT 'Approved', uploaded_by VARCHAR(255), created_at DATE NOT NULL) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await pool.query(`CREATE TABLE IF NOT EXISTS ${table('categories')} (id VARCHAR(120) PRIMARY KEY, name VARCHAR(255) NOT NULL, icon VARCHAR(80), track_count INT NOT NULL DEFAULT 0, languages TEXT, description TEXT, cover_image TEXT, is_popular TINYINT(1) NOT NULL DEFAULT 0) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await pool.query(`CREATE TABLE IF NOT EXISTS ${table('settings')} (setting_key VARCHAR(80) PRIMARY KEY, setting_value LONGTEXT NOT NULL) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
}
const parseSong = (r) => ({ id:r.id,title:r.title,artist:r.artist,category:r.category,language:r.language,coverImage:r.cover_image||'',lyrics:r.lyrics,chordsLyrics:r.chords_lyrics||'',defaultKey:r.default_key||'C',bpm:r.bpm||undefined,tempo:r.tempo||'',videoUrl:r.video_url||'',audioUrl:r.audio_url||'',mediaLinks:JSON.parse(r.media_links||'[]'),isPinned:Boolean(r.is_pinned),isFavorite:Boolean(r.is_favorite),views:r.views,year:r.year||undefined,status:r.status,uploadedBy:r.uploaded_by||'',createdAt:String(r.created_at).slice(0,10) });
const auth = (req,res,next) => { const token=req.cookies.el_roi_admin; if(!token||!sessions.has(token)) return res.status(401).json({error:'Admin authentication required'}); next(); };
app.get('/api/health', async (_req,res) => { try { await pool.query('SELECT 1'); res.json({ok:true,database:'connected'}); } catch { res.status(503).json({ok:false,database:'unavailable'}); } });
app.post('/api/admin/login',(req,res)=>{ if(!process.env.ADMIN_PASSCODE||req.body?.passcode!==process.env.ADMIN_PASSCODE) return res.status(401).json({error:'Invalid passcode'}); const token=crypto.randomBytes(32).toString('hex'); sessions.set(token,Date.now()); const flags=`HttpOnly; Path=/; SameSite=Lax; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`; res.setHeader('Set-Cookie',`el_roi_admin=${encodeURIComponent(token)}; ${flags}`); res.json({ok:true}); });
app.get('/api/bootstrap',async(_req,res)=>{ try { const [songs]=await pool.query(`SELECT * FROM ${table('songs')} ORDER BY created_at DESC, id DESC`); const [categories]=await pool.query(`SELECT * FROM ${table('categories')} ORDER BY name`); const [settings]=await pool.query(`SELECT setting_value FROM ${table('settings')} WHERE setting_key='global'`); res.json({songs:songs.map(parseSong),categories:categories.map(c=>({id:c.id,name:c.name,icon:c.icon||'music',trackCount:c.track_count,languages:JSON.parse(c.languages||'[]'),description:c.description||'',coverImage:c.cover_image||'',isPopular:Boolean(c.is_popular)})),settings:settings[0]?JSON.parse(settings[0].setting_value):{}}); } catch(e) { res.status(500).json({error:e.message}); } });
app.put('/api/settings',auth,async(req,res)=>{ await pool.query(`INSERT INTO ${table('settings')} (setting_key,setting_value) VALUES ('global',?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)`,[JSON.stringify(req.body)]); res.json(req.body); });
app.post('/api/songs',auth,async(req,res)=>{ const s={...req.body,id:`song-${crypto.randomUUID()}`,createdAt:new Date().toISOString().slice(0,10),views:0}; const values=[s.id,s.title||'',s.artist||'',s.category||'',s.language||'English',s.coverImage||'',s.lyrics||'',s.chordsLyrics||'',s.defaultKey||'C',s.bpm||null,s.tempo||'',s.videoUrl||'',s.audioUrl||'',JSON.stringify(s.mediaLinks||[]),s.isPinned?1:0,s.isFavorite?1:0,0,s.year||null,s.status||'Approved',s.uploadedBy||'',s.createdAt]; await pool.query(`INSERT INTO ${table('songs')} (id,title,artist,category,language,cover_image,lyrics,chords_lyrics,default_key,bpm,tempo,video_url,audio_url,media_links,is_pinned,is_favorite,views,year,status,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,values); res.status(201).json(s); });
app.put('/api/songs/:id',auth,async(req,res)=>{ const [rows]=await pool.query(`SELECT * FROM ${table('songs')} WHERE id=?`,[req.params.id]); if(!rows[0]) return res.sendStatus(404); const s={...parseSong(rows[0]),...req.body,id:req.params.id}; await pool.query(`UPDATE ${table('songs')} SET title=?,artist=?,category=?,language=?,cover_image=?,lyrics=?,chords_lyrics=?,default_key=?,bpm=?,tempo=?,video_url=?,audio_url=?,media_links=?,is_pinned=?,is_favorite=?,views=?,year=?,status=?,uploaded_by=? WHERE id=?`,[s.title,s.artist,s.category,s.language,s.coverImage||'',s.lyrics,s.chordsLyrics||'',s.defaultKey||'C',s.bpm||null,s.tempo||'',s.videoUrl||'',s.audioUrl||'',JSON.stringify(s.mediaLinks||[]),s.isPinned?1:0,s.isFavorite?1:0,s.views||0,s.year||null,s.status||'Approved',s.uploadedBy||'',req.params.id]); res.json(s); });
app.delete('/api/songs/:id',auth,async(req,res)=>{await pool.query(`DELETE FROM ${table('songs')} WHERE id=?`,[req.params.id]);res.sendStatus(204);});
app.post('/api/categories',auth,async(req,res)=>{const c={...req.body,id:`${String(req.body.name).toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now()}`,trackCount:0};await pool.query(`INSERT INTO ${table('categories')} (id,name,icon,track_count,languages,description,cover_image,is_popular) VALUES (?,?,?,?,?,?,?,?)`,[c.id,c.name,c.icon||'music',0,JSON.stringify(c.languages||[]),c.description||'',c.coverImage||'',c.isPopular?1:0]);res.status(201).json(c);});
app.delete('/api/categories/:id',auth,async(req,res)=>{await pool.query(`DELETE FROM ${table('categories')} WHERE id=?`,[req.params.id]);res.sendStatus(204);});
const root=path.dirname(fileURLToPath(import.meta.url)); app.use(express.static(path.join(root,'dist'))); app.get('*',(_req,res)=>res.sendFile(path.join(root,'dist','index.html')));
initDb().then(()=>app.listen(port,()=>console.log(`El Roi Tunes listening on ${port}`))).catch(e=>{console.error('Database initialization failed:',e.message);process.exit(1);});
