import React, { useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, Check, ChevronRight, FolderPlus, LayoutDashboard, MoreVertical, Pencil, Plus, Search, Trash2, Upload, X } from 'lucide-react';
import { Category, Song } from '../types';
import { motion } from 'motion/react';

interface AdminPanelProps { songs: Song[]; categories: Category[]; onClose: () => void; onSaveSong: (data: Omit<Song, 'id' | 'createdAt' | 'views'>, id?: string) => void; onDeleteSong: (id: string) => void; onAddCategory: (data: Omit<Category, 'id' | 'trackCount'>) => void; onDeleteCategory: (id: string) => void; }
type AdminPage = 'dashboard' | 'songs' | 'categories';

const blankSong = (category = 'Worship'): Omit<Song, 'id' | 'createdAt' | 'views'> => ({ title: '', artist: '', category, language: 'English', coverImage: '', lyrics: '', chordsLyrics: '', defaultKey: 'C', bpm: 72, tempo: '4/4', videoUrl: '', audioUrl: '', isPinned: false, isFavorite: false, year: new Date().getFullYear(), status: 'Approved', uploadedBy: 'Admin', timestamps: [] });

export const AdminPanel: React.FC<AdminPanelProps> = ({ songs, categories, onClose, onSaveSong, onDeleteSong, onAddCategory, onDeleteCategory }) => {
  const [page, setPage] = useState<AdminPage>('dashboard');
  const [editing, setEditing] = useState<Song | null>(null);
  const [showEditor, setShowEditor] = useState(false);
  const [query, setQuery] = useState('');
  const [showCategoryForm, setShowCategoryForm] = useState(false);
  const [notice, setNotice] = useState('');
  const approved = songs.filter((song) => song.status === 'Approved').length;

  const openNewSong = () => { setEditing(null); setShowEditor(true); };
  const saveSong = (data: Omit<Song, 'id' | 'createdAt' | 'views'>) => { onSaveSong(data, editing?.id); setShowEditor(false); setEditing(null); setNotice('Song saved'); setTimeout(() => setNotice(''), 2400); };
  const filteredSongs = useMemo(() => songs.filter((song) => `${song.title} ${song.artist} ${song.language}`.toLowerCase().includes(query.toLowerCase())), [songs, query]);

  const nav = [{ id: 'dashboard' as AdminPage, label: 'Overview', icon: <LayoutDashboard className="w-4 h-4" /> }, { id: 'songs' as AdminPage, label: 'Songs & lyrics', icon: <BookOpen className="w-4 h-4" /> }, { id: 'categories' as AdminPage, label: 'Categories', icon: <FolderPlus className="w-4 h-4" /> }];
  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-[#f4f6f1] text-[#1d2b20]">
    <header className="sticky top-0 z-20 border-b border-[#dfe5da] bg-[#f4f6f1]/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><button onClick={onClose} aria-label="Exit admin panel" className="rounded-full p-2 hover:bg-[#e4ecdf]"><ArrowLeft className="w-5 h-5" /></button><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#a26b3d]">Private workspace</p><h1 className="font-serif text-xl font-semibold text-[#29402a]">Songbook admin</h1></div></div><button onClick={openNewSong} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[#29402a] px-4 text-sm font-semibold text-white"><Plus className="w-4 h-4" /><span className="hidden sm:inline">Add song</span></button></div><nav className="mx-auto flex max-w-6xl gap-1 overflow-x-auto px-4 pb-2 sm:px-6">{nav.map((item) => <button key={item.id} onClick={() => setPage(item.id)} className={`flex min-h-10 shrink-0 items-center gap-2 rounded-full px-4 text-sm font-semibold ${page === item.id ? 'bg-[#29402a] text-white' : 'text-[#657368] hover:bg-[#e4ecdf]'}`}>{item.icon}{item.label}</button>)}</nav></header>
    <main className="mx-auto max-w-6xl px-4 py-6 pb-20 sm:px-6">{notice && <div className="fixed bottom-5 left-1/2 z-[80] -translate-x-1/2 rounded-full bg-[#29402a] px-5 py-3 text-sm font-semibold text-white shadow-xl"><Check className="mr-2 inline w-4 h-4" />{notice}</div>}
      {page === 'dashboard' && <Dashboard songs={songs} categories={categories} onOpenSongs={() => setPage('songs')} onOpenNew={openNewSong} />}
      {page === 'songs' && <section><div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[#a26b3d]">Content library</p><h2 className="font-serif text-3xl text-[#29402a]">Songs & lyrics</h2><p className="mt-1 text-sm text-[#718073]">Add, edit, publish, or remove every song.</p></div><button onClick={openNewSong} className="hidden min-h-11 items-center gap-2 rounded-xl bg-[#29402a] px-4 text-sm font-semibold text-white sm:flex"><Plus className="w-4 h-4" /> Add song</button></div><div className="relative mb-4"><Search className="absolute left-4 top-1/2 w-4 h-4 -translate-y-1/2 text-[#718073]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, artist, language" className="w-full rounded-2xl border border-[#d9ded4] bg-white py-3.5 pl-11 pr-4 text-sm outline-none focus:border-[#557b55]" /></div><div className="space-y-2">{filteredSongs.map((song) => <SongRow key={song.id} song={song} onEdit={() => { setEditing(song); setShowEditor(true); }} onDelete={() => { if (confirm(`Delete “${song.title}”?`)) onDeleteSong(song.id); }} />)}</div>{filteredSongs.length === 0 && <Empty text="No songs match your search." />}</section>}
      {page === 'categories' && <CategoryPage categories={categories} songs={songs} onAdd={onAddCategory} onDelete={onDeleteCategory} showForm={showCategoryForm} setShowForm={setShowCategoryForm} />}
    </main>
    {showEditor && <SongEditor initial={editing ? { ...editing } : blankSong(categories[0]?.name)} categories={categories} onClose={() => setShowEditor(false)} onSave={saveSong} />}
  </div>;
};

const Dashboard: React.FC<{ songs: Song[]; categories: Category[]; onOpenSongs: () => void; onOpenNew: () => void }> = ({ songs, categories, onOpenSongs, onOpenNew }) => <section><div className="mb-7"><p className="text-sm font-semibold text-[#a26b3d]">Good morning, admin</p><h2 className="font-serif text-4xl text-[#29402a]">Your songbook at a glance.</h2><p className="mt-2 max-w-lg text-sm text-[#718073]">Keep lyrics accurate, organized, and ready for everyone to sing.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Songs', songs.length], ['Published', songs.filter((s) => s.status === 'Approved').length], ['Languages', new Set(songs.map((s) => s.language)).size], ['Categories', categories.length]].map(([label, value]) => <div key={label} className="rounded-2xl border border-[#dfe5da] bg-white p-4"><p className="text-xs font-semibold text-[#718073]">{label}</p><p className="mt-2 text-3xl font-semibold text-[#29402a]">{value}</p></div>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><button onClick={onOpenNew} className="rounded-2xl bg-[#29402a] p-5 text-left text-white"><Upload className="mb-8 h-6 w-6 text-[#e7b485]" /><p className="text-lg font-semibold">Upload a song</p><p className="mt-1 text-sm text-white/65">Add lyrics, chords, media, and publishing details.</p></button><button onClick={onOpenSongs} className="rounded-2xl border border-[#dfe5da] bg-white p-5 text-left hover:bg-[#f0f4ed]"><BookOpen className="mb-8 h-6 w-6 text-[#a26b3d]" /><p className="text-lg font-semibold text-[#29402a]">Manage library</p><p className="mt-1 text-sm text-[#718073]">Edit existing content and review what is published.</p></button></div><div className="mt-6 rounded-2xl border border-[#dfe5da] bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-semibold text-[#29402a]">Recently added</h3><button onClick={onOpenSongs} className="text-sm font-semibold text-[#557b55]">View all <ChevronRight className="inline h-4 w-4" /></button></div><div className="mt-3 divide-y divide-[#edf0e9]">{songs.slice(0, 4).map((song) => <div key={song.id} className="flex items-center gap-3 py-3"><div className="h-9 w-9 overflow-hidden rounded-lg bg-[#e8eee1]"><img src={song.coverImage} alt="" className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{song.title}</p><p className="text-xs text-[#718073]">{song.language} · {song.status}</p></div></div>)}</div></div></section>;

const SongRow: React.FC<{ song: Song; onEdit: () => void; onDelete: () => void }> = ({ song, onEdit, onDelete }) => <div className="flex items-center gap-3 rounded-2xl border border-[#dfe5da] bg-white p-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-[#e8eee1]"><img src={song.coverImage} alt="" className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><p className="truncate font-semibold text-[#29402a]">{song.title}</p><p className="truncate text-sm text-[#718073]">{song.artist}</p><div className="mt-1 flex gap-2 text-[11px] font-semibold"><span className="rounded-full bg-[#e8eee1] px-2 py-1 text-[#557b55]">{song.language}</span><span className={`rounded-full px-2 py-1 ${song.status === 'Approved' ? 'bg-[#e8eee1] text-[#557b55]' : 'bg-[#fff0da] text-[#a26b3d]'}`}>{song.status}</span></div></div><button onClick={onEdit} aria-label={`Edit ${song.title}`} className="rounded-full p-2 text-[#557b55] hover:bg-[#e8eee1]"><Pencil className="w-4 h-4" /></button><button onClick={onDelete} aria-label={`Delete ${song.title}`} className="rounded-full p-2 text-[#ad473d] hover:bg-[#fff0ed]"><Trash2 className="w-4 h-4" /></button></div>;

const CategoryPage: React.FC<{ categories: Category[]; songs: Song[]; onAdd: (data: Omit<Category, 'id' | 'trackCount'>) => void; onDelete: (id: string) => void; showForm: boolean; setShowForm: (value: boolean) => void }> = ({ categories, songs, onAdd, onDelete, showForm, setShowForm }) => { const [name, setName] = useState(''); const [description, setDescription] = useState(''); const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; onAdd({ name: name.trim(), description: description.trim() || 'Song collection', icon: 'music', languages: ['EN'], coverImage: '' }); setName(''); setDescription(''); setShowForm(false); }; return <section><div className="mb-5 flex items-end justify-between"><div><p className="text-sm font-semibold text-[#a26b3d]">Organization</p><h2 className="font-serif text-3xl text-[#29402a]">Categories</h2><p className="mt-1 text-sm text-[#718073]">Group songs so people can find them quickly.</p></div><button onClick={() => setShowForm(!showForm)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#29402a] px-4 text-sm font-semibold text-white"><Plus className="w-4 h-4" /><span className="hidden sm:inline">New category</span></button></div>{showForm && <form onSubmit={submit} className="mb-4 rounded-2xl border border-[#dfe5da] bg-white p-4 space-y-3"><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Category name" className="w-full rounded-xl border border-[#d9ded4] px-3 py-3 text-sm" /><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Short description" className="w-full rounded-xl border border-[#d9ded4] px-3 py-3 text-sm" /><button className="rounded-xl bg-[#29402a] px-4 py-3 text-sm font-semibold text-white">Create category</button></form>}<div className="grid gap-3 sm:grid-cols-2">{categories.map((category) => <div key={category.id} className="flex items-center gap-3 rounded-2xl border border-[#dfe5da] bg-white p-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e8eee1] text-[#557b55]"><FolderPlus className="w-5 h-5" /></div><div className="min-w-0 flex-1"><p className="font-semibold text-[#29402a]">{category.name}</p><p className="text-xs text-[#718073]">{songs.filter((song) => song.category === category.name).length} songs</p></div><button onClick={() => { if (confirm(`Delete “${category.name}”?`)) onDelete(category.id); }} aria-label={`Delete ${category.name}`} className="rounded-full p-2 text-[#ad473d] hover:bg-[#fff0ed]"><Trash2 className="w-4 h-4" /></button></div>)}</div></section>; };

const Empty: React.FC<{ text: string }> = ({ text }) => <div className="rounded-2xl border border-dashed border-[#cfd8ca] p-10 text-center text-sm text-[#718073]">{text}</div>;

const SongEditor: React.FC<{ initial: Omit<Song, 'id' | 'createdAt' | 'views'> & Partial<Pick<Song, 'id'>>; categories: Category[]; onClose: () => void; onSave: (song: Omit<Song, 'id' | 'createdAt' | 'views'>) => void }> = ({ initial, categories, onClose, onSave }) => {
  const [song, setSong] = useState({ ...initial });
  const update = <K extends keyof typeof song>(key: K, value: typeof song[K]) => setSong((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!song.title.trim() || !song.lyrics.trim()) return; const { id: _id, ...data } = song; onSave(data as Omit<Song, 'id' | 'createdAt' | 'views'>); };
  return <div className="fixed inset-0 z-[75] overflow-y-auto bg-[#f4f6f1]"><div className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-[#dfe5da] bg-[#f4f6f1]/95 px-4 backdrop-blur-xl"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#a26b3d]">Song editor</p><h2 className="font-serif text-xl text-[#29402a]">{initial.id ? 'Edit song' : 'Add a new song'}</h2></div><button onClick={onClose} aria-label="Close editor" className="rounded-full p-2 hover:bg-[#e4ecdf]"><X className="w-5 h-5" /></button></div><form onSubmit={submit} className="mx-auto max-w-3xl space-y-5 px-4 py-6 pb-20 sm:px-6"><div className="rounded-2xl border border-[#dfe5da] bg-white p-4 space-y-4"><h3 className="font-semibold text-[#29402a]">Basic details</h3><div className="grid gap-3 sm:grid-cols-2"><Field label="Song title *" value={song.title} onChange={(v) => update('title', v)} /><Field label="Artist / author" value={song.artist} onChange={(v) => update('artist', v)} /><Select label="Language" value={song.language} options={['English', 'Hindi', 'Nepali', 'Spanish', 'Portuguese']} onChange={(v) => update('language', v)} /><Select label="Category" value={song.category} options={categories.map((category) => category.name)} onChange={(v) => update('category', v)} /><Field label="Cover image URL" value={song.coverImage} onChange={(v) => update('coverImage', v)} /><Field label="Default key" value={song.defaultKey} onChange={(v) => update('defaultKey', v)} /><Field label="BPM" value={String(song.bpm || '')} onChange={(v) => update('bpm', Number(v) || undefined)} /><Select label="Status" value={song.status} options={['Approved', 'Pending', 'Draft']} onChange={(v) => update('status', v as Song['status'])} /></div></div><div className="rounded-2xl border border-[#dfe5da] bg-white p-4 space-y-4"><h3 className="font-semibold text-[#29402a]">Words & chords</h3><TextArea label="Lyrics *" value={song.lyrics} onChange={(v) => update('lyrics', v)} placeholder="Paste the complete lyrics here…" /><TextArea label="Chords lyrics" value={song.chordsLyrics} onChange={(v) => update('chordsLyrics', v)} placeholder="Optional chord notation, for example [G]Amazing grace…" /></div><div className="rounded-2xl border border-[#dfe5da] bg-white p-4 space-y-4"><h3 className="font-semibold text-[#29402a]">Media & publishing</h3><Field label="YouTube / video URL" value={song.videoUrl || ''} onChange={(v) => update('videoUrl', v)} /><Field label="Audio URL" value={song.audioUrl || ''} onChange={(v) => update('audioUrl', v)} /><Field label="Uploaded by" value={song.uploadedBy} onChange={(v) => update('uploadedBy', v)} /></div><button type="submit" className="w-full rounded-2xl bg-[#29402a] py-4 text-sm font-semibold text-white hover:bg-[#203322]">Save song to library</button></form></div>;
};

const Field: React.FC<{ label: string; value: string; onChange: (value: string) => void }> = ({ label, value, onChange }) => <label className="block text-sm font-semibold text-[#29402a]">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#d9ded4] bg-[#fbfcfa] px-3 py-3 text-sm font-normal outline-none focus:border-[#557b55]" /></label>;
const TextArea: React.FC<{ label: string; value: string; onChange: (value: string) => void; placeholder: string }> = ({ label, value, onChange, placeholder }) => <label className="block text-sm font-semibold text-[#29402a]">{label}<textarea required={label.includes('*')} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} rows={9} className="mt-1.5 w-full resize-y rounded-xl border border-[#d9ded4] bg-[#fbfcfa] px-3 py-3 text-sm font-normal leading-relaxed outline-none focus:border-[#557b55]" /></label>;
const Select: React.FC<{ label: string; value: string; options: string[]; onChange: (value: string) => void }> = ({ label, value, options, onChange }) => <label className="block text-sm font-semibold text-[#29402a]">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#d9ded4] bg-[#fbfcfa] px-3 py-3 text-sm font-normal outline-none focus:border-[#557b55]">{options.map((option) => <option key={option}>{option}</option>)}</select></label>;
